[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true
